import "./globals.css";
import Navbar from "./components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>
          <div className="section">
            <div className="container">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
